// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBseVdS289pB72W5tcfezF7fUUJ_Onn5s',
    appId: '1:1057691350660:web:003689bc323383833434d1',
    messagingSenderId: '1057691350660',
    projectId: 'cleanrail-c3260',
    authDomain: 'cleanrail-c3260.firebaseapp.com',
    storageBucket: 'cleanrail-c3260.firebasestorage.app',
    measurementId: 'G-27X7G98Y3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmv15f9082cVHGNUOdaWNjT3jv3sk66VI',
    appId: '1:1057691350660:android:1eb0980a0ded13fd3434d1',
    messagingSenderId: '1057691350660',
    projectId: 'cleanrail-c3260',
    storageBucket: 'cleanrail-c3260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCFyXqeunZlPRkPSEknsfPzGiKhINoRE',
    appId: '1:1057691350660:ios:c907868042834a703434d1',
    messagingSenderId: '1057691350660',
    projectId: 'cleanrail-c3260',
    storageBucket: 'cleanrail-c3260.firebasestorage.app',
    iosBundleId: 'com.example.myrailway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCFyXqeunZlPRkPSEknsfPzGiKhINoRE',
    appId: '1:1057691350660:ios:c907868042834a703434d1',
    messagingSenderId: '1057691350660',
    projectId: 'cleanrail-c3260',
    storageBucket: 'cleanrail-c3260.firebasestorage.app',
    iosBundleId: 'com.example.myrailway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBseVdS289pB72W5tcfezF7fUUJ_Onn5s',
    appId: '1:1057691350660:web:95b4725a77a4b6193434d1',
    messagingSenderId: '1057691350660',
    projectId: 'cleanrail-c3260',
    authDomain: 'cleanrail-c3260.firebaseapp.com',
    storageBucket: 'cleanrail-c3260.firebasestorage.app',
    measurementId: 'G-3HXFKV2V2R',
  );
}
